### ISSUE TITLE
[FEAT] Character 뷰 애니메이션 구현

### ISSUE THREAD

**Issue by heerucan** [TeamCatchMe/CatchMe-If-You-iOS#13]
## 💡 Issue
Character 뷰 스크롤 애니메이션 구현

## 📝  todo
- [x] 스크롤 시 캐릭터 위치 고정시키기
- [x] 캐릭터 리포트 headerView가 캐릭터 가리지 않도록 설정값 주기

**Comment by 5anniversary** [comment]
👀
